#!/bin/bash

alias mv='mv -f'
alias rm='rm -f'
alias cp='cp -f'

export LIBDIR="lib"
export BINDIR="bin"

export FC="ifort -lmpi -g -xHost -O3 -align -ansi-alias -mcmodel=medium -traceback"
export CC="icc -lmpi -g -xHost -O3 -align -ansi-alias -mcmodel=medium -traceback"
export CXX="icpc -lmpi -g -xHost -O3 -align -ansi-alias -mcmodel=medium -traceback -restrict"
export LAPACKLIB="-mkl=sequential" 
##export FC="ifort -lmpi"
##export CC="icc -lmpi"
##export CXX="icpc -lmpi"
##export LAPACKLIB="-llapack"

num=$#
originalarguments=$@

if [[ $num -eq 0 ]]
then
  echo 'McCompile: No include file supplied.'
  echo '  Usage: McCompile file1.inc file2.inc ...'
  goto finish
fi 

testfile=$LIBDIR/libnest3.a
if [ ! -e $testfile ]
then
  gmake -C multinest
else
  echo "libnest3.a exists, no need to remake."
fi  

echo "  "

touch src/params.f90; mv src/params.f90 params_old.f90

for incfile in $originalarguments
do
  echo "Compiling "$incfile
  exefile=`echo $incfile | sed "s/inc/exe/"`
  touch $exefile; rm $exefile
  
  simulate=`grep simulate/ $incfile | cut -d'.' -f 2`  

  if [ $simulate == "true" ]
  then
    
    echo "simulation has been disabled."
    exit 1

  else
  	if [ $simulate == "false" ]
	then
		cp src/params_MakeData_dummy.f90 src/params_MakeData.f90
		cp src/MakeData_dummy.f90 src/MakeData.f90
		echo "Inference mode, using MakeData_dummy.f90"
	else
		echo "Error: simulate has value "$simulate
	fi 
  fi
      
  cp $incfile src/params.f90
  
  echo " "
  gmake McAdam
  if [ -e $BINDIR/McAdam ]
  then
    mv $BINDIR/McAdam $BINDIR/$exefile
  else 
    echo "Compilation failed: $BINDIR/$exefile not created."
  fi
    
  echo " "
    
done

i=1

for incfile in $originalargmuments
do
  exefile=`echo $incfile | sed "s/inc/exe/"`
  if [ -e $BINDIR/$exefile ]
  then 
    echo "Compiled "$BINDIR/$exefile" using "$incfile
  else
    echo "Failed to compile "$BINDIR/$exefile" using "$incfile
  fi
done

mv params_old.f90 src/params.f90
echo " "
 
exit 0
